Description:
    Leon / Udacity

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String


Resources:

    # IAM Role to allow EC2 Session Manager to access our server
    RoleForSSMAccess: 
        Type: "AWS::IAM::Role"
        Properties:
            AssumeRolePolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Principal:
                    Service:
                      - ec2.amazonaws.com
                  Action:
                    - 'sts:AssumeRole'
            ManagedPolicyArns:
              - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    # Instance Profile
    ServerInstanceProfile: 
        Type: "AWS::IAM::InstanceProfile"
        Properties: 
            Roles: 
              - !Ref RoleForSSMAccess

    WebServerSecGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allow http to our hosts and SSH from local only
            VpcId:
                Fn::ImportValue:
                    !Sub "${EnvironmentName}-VPCID"
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 80
                  ToPort: 80
                  CidrIp: 0.0.0.0/0
                - IpProtocol: tcp
                  FromPort: 22
                  ToPort: 22
                  CidrIp: 0.0.0.0/0
            SecurityGroupEgress:
                - IpProtocol: tcp
                  FromPort: 0
                  ToPort: 65535
                  CidrIp: 0.0.0.0/0

    leonswebServerInstance:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: ami-0022f774911c1d690
            InstanceType: t2.micro
            IamInstanceProfile: !Ref ServerInstanceProfile
            NetworkInterfaces:
              - GroupSet:
                  - Ref: "WebServerSecGroup"
                DeviceIndex: "0"
                SubnetId: subnet-09dde53a1927de31e
