Description:
    Leon / Udacity

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
    myUsername:
        Description: Any username
        Type: String 
    myPassword:
        Description: A password with at least 8 characters
        Type: String  

Resources:

    myDBSubnetGroup1:
        Type: "AWS::RDS::DBSubnetGroup"
        Properties: 
          DBSubnetGroupDescription: "Subnets to use for the DB"
          DBSubnetGroupName: "Subnet Group"
          # Replace these IDs, as applicable to you
          SubnetIds:
            - subnet-09c885c90f309ab09
            - subnet-05750962fb36f67f4



    MyDB: 
        Type: "AWS::RDS::DBInstance"
        Properties: 
          # Replace this ID, as applicable to you. I have used the default SG. 
          VPCSecurityGroups: [sg-0db4c3839a3cc307a]
          PubliclyAccessible: false
          MultiAZ: false
          AllocatedStorage: 20
          DBInstanceClass: db.t2.small
          Engine: "mysql"
          MasterUsername: !Sub "${myUsername}"
          MasterUserPassword: !Sub "${myPassword}"
          DBSubnetGroupName: !Ref myDBSubnetGroup1
        DeletionPolicy: "Retain"
      
